services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9091:9091"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka
    depends_on:
      - zookeeper

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db

  server:
    image: node:18-alpine
    restart: unless-stopped
    working_dir: /srv/server
    tty: true
    volumes:
      - ./:/srv/server
    ports:
      - 4040:4040
    networks:
      - kafka
    depends_on:
      - mongodb

networks:
  kafka:
    driver: bridge
